net:
  hosts:
    fusion1-isr4451:
      ansible_host: 192.168.200.1
      fusion: true
    fusion2-isr4451:
      ansible_host: 192.168.200.2
      fusion: true
    border1-9500:
      ansible_host: 192.168.200.3
      border: true
      control_plane: true
    border2-9500:
      ansible_host: 192.168.200.4
      border: true
      control_plane: true
    edge1-9300:
      ansible_host: 192.168.200.5
      edge: true 
    edge2-9300:
      ansible_host: 192.168.200.6
      edge: true
