---
- name: Show version
  hosts: all
  gather_facts: false

  tasks:
  - name: show version
    cisco.ios.ios_command:
      commands: show version
    register: show_version

  - name: print show version
    ansible.builtin.debug:
      msg: "{{show_version}}"
