loopback0_interface_ip: 192.168.200.4 # Loopback interface ip address
handoff_interface_local:  TenGigabitEthernet 1/0/1
vrfs:
    - vrf: VN1
      handoff_vlan: 2020
      handoff_ip_address: 192.168.220.6/30
    - vrf: VN2
      handoff_vlan: 2021
      handoff_ip_address:  192.168.220.10/30
 
