type: router
vrfs:
  - vrf: GRT
    handoffs:
      - handoff_prefix: 192.168.220.0/30
        handoff_vlan: 2020
        handoff_interface: GigabitEthernet0/0/2
        remote_device: border1-9500
      - handoff_prefix: 192.168.220.12/30
        handoff_vlan: 2023
        handoff_interface: GigabitEthernet0/0/3
        remote_device: border2-9500
  - vrf: VN2
    handoffs:
      - handoff_prefix: 192.168.220.8/30
        handoff_vlan: 2022
        handoff_interface: GigabitEthernet0/0/4
        remote_device: border1-9500
      - handoff_prefix: 192.168.220.20/30
        handoff_vlan: 2025
        handoff_interface: GigabitEthernet0/0/5
        remote_device: border2-9500

