type: switch
vrfs:
  - vrf: VN1
    handoffs:
      - handoff_ip_address: 192.168.220.1/30
        handoff_vlan: 2020
        handoff_interface: GigabitEthernet0/0/2
  - vrf: VN2
    handoffs:
      - handoff_ip_address: 192.168.220.5/30
        handoff_vlan: 2021
        handoff_interface: GigabitEthernet0/0/3
 

