---
- name: Create directory for configs
  ansible.builtin.file:
    path: "files/{{inventory_hostname}}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Create external border config
  ansible.builtin.template:
    src: templates/border-dynamic-external.j2
    dest: 'files/{{inventory_hostname}}/border-external.conf'
  delegate_to: localhost

# - name: Create external border config in device
#   cisco.ios.ios_config:
#     src: templates/dynamic-external-border.j2
#     save_when: never
