- name: Create directory for configs
  ansible.builtin.file:
    path: "files/{{inventory_hostname}}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Creating Border VRFs variable
  ansible.builtin.set_fact:
    borders_vrfs: []

- name: Gathering Border VRFs
  ansible.builtin.set_fact:
    borders_vrfs: "{{ borders_vrfs + [hostvars[item].vrfs] }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].border is defined

- name: Create fusion BGP config
  ansible.builtin.template:
    src: templates/fusion-bgp.j2
    dest: 'files/{{inventory_hostname}}/fusion-bgp.conf'
  delegate_to: localhost

- name: Create fusion BGP config in device
  cisco.ios.ios_config:
    src: templates/fusion-bgp.j2
    save_when: never
  when: 
    - not skip_deploy | bool
